### PR TITLE
Updating vendor data in the OASIS Discovery tool

### PR DESCRIPTION
**Pull request by dsiddy**
This pull request addresses #419, and seeks to fulfill the requirements of [the associated micro-purchase auction](https://micropurchase.18f.gov/auctions/30).

### CODE REVIEW

**Comment by mtorres253** [comment]
Hi @dsiddy if you are ready for us to review, let us know by clicking the "I'm done" button on the auction page:

https://micropurchase.18f.gov/auctions/30

We're excited to work with you to get this merged.

**Comment by stvnrlly** [comment]
Hey there, @dsiddy, thanks for this pull request!

A cursory look at the CSVs is 👍 , and thank you for pointing out the missing FSS contract numbers. I will look into that and see if that's expected, but I don't think that will affect approval.

I'm more concerned about the second acceptance criterion: Django fixtures and a fixture-creation command. I'm not seeing a new Django fixture or anything in this pull request that would reproduce the manual data-crunching steps in the README and produce a fixture to be loaded into the site. Am I missing something? I think that I would expect to see a Bash command and a new JSON file to fulfill that acceptance criterion.

**Comment by mtorres253** [comment]
Thanks @stvnrlly. Let us know @dsiddy

**Comment by mtorres253** [comment]
Hmmm. checks are failing now. Would you take a look and let us know @dsiddy?

**Comment by dsiddy** [comment]
Looking into it at the moment. Will give you an update soon.

-----

my public key
<https://pgp.mit.edu/pks/lookup?op=get&search=0x3F774E8546030565>

**Comment by mtorres253** [comment]
Thank you!

**Comment by dsiddy** [comment]
Quick update: it seems that my stand-alone script was causing trouble with
the existing vendors.json API fixture. I've since rolled the logic into the
load_vendors and check_sam commands. It's easy enough to generate a working
fixture from the CSV files alone, but it seems woefully incomplete without
the SAM data, which I'm waiting on at this point. Once I've verified the
fixture file thus generated, I'll run the test suite locally, then post my
changes.

-----

my public key
<https://pgp.mit.edu/pks/lookup?op=get&search=0x3F774E8546030565>

**Comment by dsiddy** [comment]
Never mind; I see what's going on. Need to step away from the keyboard for a bit, but I'll have everything passing muster soon.

**Comment by dsiddy** [comment]
@stvnrlly and @mtorres253, thank you both for your patience. I both acknowledge and apologize for my failure to make the deadline.

**Comment by mtorres253** [comment]
Thanks @dsiddy

**Comment by stvnrlly** [comment]
Thanks, @dsiddy. We accept this pull request (cc @adelevie).

**Comment by stvnrlly** [comment]
Hey @dsiddy, sorry for letting this set for so long. This project was ported to cloud.gov, and we waited until after that was done to fit this in.

As a result of the porting, it looks like some of the work done here may no longer be necessary. I'm going to take care of the trimming and merging, but didn't want you to be surprised and wanted to make sure that you know that it doesn't reflect on the work you did.

**Comment by stvnrlly** [comment]
Coming back around to this, it looks like no post-porting changes are required here and everything seems to run well with the cloud.gov code. That work took place in the [`cloudfoundry`](https://github.com/18F/discovery/tree/cloudfoundry) branch, and it looks like there's a tiny conflict because some `master` branch code is not in the `cloudfoundry` branch for some reason.

I'd go ahead and change the base of this branch to `cloudfoundry`, but I don't want to make decisions for whoever may ultimately be deploying this code, so I'm going to leave things as-is with this note.

**Comment by jseppi** [comment]
Any update on this? Will the data be updated once the migration to GovCloud finishes?

**Comment by stvnrlly** [comment]
@jseppi Yes, the migration to GovCloud is still progressing and I'm keeping tabs on it to get this merged as part of that.

**Pull request merged**
